name: Build Datapusher image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: datapusher

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t ${IMAGE_NAME} .
      
      - name: Login to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          IMAGE_TAG=latest
          docker tag ${IMAGE_NAME} ${IMAGE_ID}:${IMAGE_TAG}
          docker push ${IMAGE_ID}:${IMAGE_TAG}
